check
Signed-off-by: Pushkar Mishra <pushkarmishra029@gmail.com>

diff --git a/.github/workflows/push2dockerhub.yml b/.github/workflows/push2dockerhub.yml
--- a/.github/workflows/push2dockerhub.yml
+++ b/.github/workflows/push2dockerhub.yml
@@ -59,31 +59,31 @@ jobs:
           push: true
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
-  update-docker-hb-description:
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v2
-    - name: Get Docker Hub token
-      id: get-docker-hb-token
-      run: |
-        curl -X POST \
-          -H "Content-Type: application/json" \
-          -d '{"username":"${{ secrets.DOCKER_USER }}","password":"${{ secrets.DOCKER_PASSWORD }}"}' \
-          https://hub.docker.com/v2/users/login \
-          -o token.json
-        token=$(jq -r .token token.json)
-        echo "token=$token" >> "$GITHUB_OUTPUT"
-        echo $token
-    - name: get token
-      run: echo ${{ steps.get-docker-hb-token.outputs.token }}
-    - name: Update Docker Hub repository description
-      run: |
-        curl -i -X PATCH \
-          -H "Content-Type: application/json" \
-          -H "Authorization: JWT ${{ steps.get-docker-hb-token.outputs.token }}" \
-          -d "{\"description\":\"${{ github.event.repository.description }}\"}" \
-          https://hub.docker.com/v2/repositories/${{ env.IMAGE_NAME }}/ || {
-            echo "API call failed with status code $?"
-            echo "Response body:"
-            cat
-            exit 1  # Explicitly fail the job
+  # update-docker-hb-description:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - uses: actions/checkout@v2
+  #   - name: Get Docker Hub token
+  #     id: get-docker-hb-token
+  #     run: |
+  #       curl -X POST \
+  #         -H "Content-Type: application/json" \
+  #         -d '{"username":"${{ secrets.DOCKER_USER }}","password":"${{ secrets.DOCKER_PASSWORD }}"}' \
+  #         https://hub.docker.com/v2/users/login \
+  #         -o token.json
+  #       token=$(jq -r .token token.json)
+  #       echo "token=$token" >> "$GITHUB_OUTPUT"
+  #       echo $token
+  #   - name: get token
+  #     run: echo ${{ steps.get-docker-hb-token.outputs.token }}
+  #   - name: Update Docker Hub repository description
+  #     run: |
+  #       curl -i -X PATCH \
+  #         -H "Content-Type: application/json" \
+  #         -H "Authorization: JWT ${{ steps.get-docker-hb-token.outputs.token }}" \
+  #         -d "{\"description\":\"${{ github.event.repository.description }}\"}" \
+  #         https://hub.docker.com/v2/repositories/${{ env.IMAGE_NAME }}/ || {
+  #           echo "API call failed with status code $?"
+  #           echo "Response body:"
+  #           cat
+  #           exit 1  # Explicitly fail the job
