check
Signed-off-by: Pushkar Mishra <pushkarmishra029@gmail.com>

diff --git a/.github/workflows/push2dockerhub.yml b/.github/workflows/push2dockerhub.yml
--- a/.github/workflows/push2dockerhub.yml
+++ b/.github/workflows/push2dockerhub.yml
@@ -59,7 +59,6 @@ jobs:
           push: true
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
-  # Update repository description step
   update-docker-hb-description:
     runs-on: ubuntu-latest
     steps:
@@ -88,3 +87,5 @@ jobs:
             echo "API call failed with status code $?"
             echo "Response body:"
             echo "${{ steps.get-docker-hb-token.outputs.token }}"
+            cat
+            exit 1  # Explicitly fail the job
